IF OBJECT_ID('tempdb..#mapSwitches') IS NOT NULL
    DROP TABLE tempdb..#mapSwitches;

SELECT *
into #mapSwitches
	
FROM (
	SELECT @source_short_name AS DB,
		'CONDITION_OCCURRENCE' AS TABLE_NAME,
		SOURCE_CODE, 
		SOURCE_VOCABULARY_ID, 
		OLD_TARGET_CONCEPT_ID, 
		OLD_TARGET_DEPRECATED, 
		NEW_TARGET_CONCEPT_ID, 
		NEW_TARGET_DOMAIN_ID,
		NEW_MAP_EXISTS_IN_OLD_VOCAB, 
		CONCEPT_NAME, 
		COUNT(*) AS PERSON_COUNT
	FROM @cdm_database_schema.CONDITION_OCCURRENCE CO
	JOIN @target_database_schema.@map_switches_table VC
		ON CO.CONDITION_SOURCE_CONCEPT_ID = VC.SOURCE_CONCEPT_ID
	LEFT JOIN @new_vocab_schema.CONCEPT C
		ON VC.SOURCE_CONCEPT_ID = C.CONCEPT_ID
	GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, OLD_TARGET_CONCEPT_ID, OLD_TARGET_DEPRECATED, 
			NEW_TARGET_CONCEPT_ID, NEW_TARGET_DOMAIN_ID, NEW_MAP_EXISTS_IN_OLD_VOCAB, CONCEPT_NAME

UNION ALL

SELECT @source_short_name AS DB,
	'PROCEDURE_OCCURRENCE' AS TABLE_NAME, 
	SOURCE_CODE, 
	SOURCE_VOCABULARY_ID, 
	OLD_TARGET_CONCEPT_ID, 
	OLD_TARGET_DEPRECATED, 
	NEW_TARGET_CONCEPT_ID, 
	NEW_TARGET_DOMAIN_ID,
	NEW_MAP_EXISTS_IN_OLD_VOCAB, 
	CONCEPT_NAME, 
	COUNT(*) AS PERSON_COUNT
FROM @cdm_database_schema.PROCEDURE_OCCURRENCE CO
JOIN @target_database_schema.@map_switches_table VC
	ON CO.PROCEDURE_SOURCE_CONCEPT_ID = VC.SOURCE_CONCEPT_ID
LEFT JOIN @new_vocab_schema.CONCEPT C
	ON VC.SOURCE_CONCEPT_ID = C.CONCEPT_ID
GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, OLD_TARGET_CONCEPT_ID, OLD_TARGET_DEPRECATED, 
		NEW_TARGET_CONCEPT_ID, NEW_TARGET_DOMAIN_ID, NEW_MAP_EXISTS_IN_OLD_VOCAB, CONCEPT_NAME
--ORDER BY COUNT(*) DESC

UNION ALL

SELECT @source_short_name AS DB,
	'DRUG_EXPOSURE' AS TABLE_NAME,
	SOURCE_CODE, 
	SOURCE_VOCABULARY_ID, 
	OLD_TARGET_CONCEPT_ID, 
	OLD_TARGET_DEPRECATED, 
	NEW_TARGET_CONCEPT_ID, 
	NEW_TARGET_DOMAIN_ID,
	NEW_MAP_EXISTS_IN_OLD_VOCAB, 
	CONCEPT_NAME, 
	COUNT(*) AS PERSON_COUNT
FROM @cdm_database_schema.DRUG_EXPOSURE CO
JOIN @target_database_schema.@map_switches_table VC
	ON CO.DRUG_SOURCE_CONCEPT_ID = VC.SOURCE_CONCEPT_ID
LEFT JOIN @new_vocab_schema.CONCEPT C
	ON VC.SOURCE_CONCEPT_ID = C.CONCEPT_ID
GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, OLD_TARGET_CONCEPT_ID, OLD_TARGET_DEPRECATED, 
	NEW_TARGET_CONCEPT_ID, NEW_TARGET_DOMAIN_ID, NEW_MAP_EXISTS_IN_OLD_VOCAB, CONCEPT_NAME
--ORDER BY COUNT(*) DESC

UNION ALL

SELECT @source_short_name AS DB,
	'MEASUREMENT' AS TABLE_NAME,
	SOURCE_CODE, 
	SOURCE_VOCABULARY_ID, 
	OLD_TARGET_CONCEPT_ID, 
	OLD_TARGET_DEPRECATED, 
	NEW_TARGET_CONCEPT_ID, 
	NEW_TARGET_DOMAIN_ID,
	NEW_MAP_EXISTS_IN_OLD_VOCAB, 
	CONCEPT_NAME, 
	COUNT(*) AS PERSON_COUNT
FROM @cdm_database_schema.MEASUREMENT CO
JOIN @target_database_schema.@map_switches_table VC
	ON CO.MEASUREMENT_SOURCE_CONCEPT_ID = VC.SOURCE_CONCEPT_ID
LEFT JOIN @new_vocab_schema.CONCEPT C
	ON VC.SOURCE_CONCEPT_ID = C.CONCEPT_ID
GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, OLD_TARGET_CONCEPT_ID, OLD_TARGET_DEPRECATED, 
NEW_TARGET_CONCEPT_ID, NEW_TARGET_DOMAIN_ID, NEW_MAP_EXISTS_IN_OLD_VOCAB, CONCEPT_NAME
--ORDER BY COUNT(*) DESC

UNION ALL

SELECT @source_short_name AS DB,
	'OBSERVATION' AS TABLE_NAME,
	SOURCE_CODE, 
	SOURCE_VOCABULARY_ID, 
	OLD_TARGET_CONCEPT_ID, 
	OLD_TARGET_DEPRECATED, 
	NEW_TARGET_CONCEPT_ID, 
	NEW_TARGET_DOMAIN_ID,
	NEW_MAP_EXISTS_IN_OLD_VOCAB, 
	CONCEPT_NAME, 
	COUNT(*) AS PERSON_COUNT
FROM @cdm_database_schema.OBSERVATION CO
JOIN @target_database_schema.@map_switches_table VC
	ON CO.OBSERVATION_SOURCE_CONCEPT_ID = VC.SOURCE_CONCEPT_ID
LEFT JOIN @new_vocab_schema.CONCEPT C
	ON VC.SOURCE_CONCEPT_ID = C.CONCEPT_ID
GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, OLD_TARGET_CONCEPT_ID, OLD_TARGET_DEPRECATED, 
	NEW_TARGET_CONCEPT_ID, NEW_TARGET_DOMAIN_ID, NEW_MAP_EXISTS_IN_OLD_VOCAB, CONCEPT_NAME
--ORDER BY COUNT(*) DESC
) a ;

insert into @target_database_schema.@map_switches_cdm_table (
    db,
    table_name,
    source_code,
	source_vocabulary_id,
	OLD_TARGET_CONCEPT_ID, 
	OLD_TARGET_DEPRECATED, 
	NEW_TARGET_CONCEPT_ID, 
	NEW_TARGET_DOMAIN_ID,
	NEW_MAP_EXISTS_IN_OLD_VOCAB, 
	CONCEPT_NAME, 
    person_count
)

SELECT *
FROM #mapSwitches;

