IF OBJECT_ID('tempdb..#newMaps') IS NOT NULL
    DROP TABLE tempdb..#newMaps;

SELECT *
into #newMaps
FROM (

	SELECT @source_short_name AS DB,
			'CONDITION_OCCURRENCE' AS CURRENT_LOCATION,
			SOURCE_CODE,
			SOURCE_VOCABULARY_ID,
			CONCEPT_NAME AS SOURCE_CONCEPT_NAME,
			TARGET_CONCEPT_ID AS NEW_TARGET_CONCEPT_ID,
			TARGET_DOMAIN_ID AS NEW_DOMAIN_ID,
			CONDITION_CONCEPT_ID AS CURRENT_CONCEPT_ID,
			COUNT(*) AS PERSON_COUNT
	FROM @cdm_database_schema.CONDITION_OCCURRENCE CO
	JOIN @target_database_schema.@new_maps_table NM
		ON CO.CONDITION_SOURCE_CONCEPT_ID = NM.SOURCE_CONCEPT_ID
	JOIN @new_vocab_schema.CONCEPT C
		ON NM.SOURCE_CONCEPT_ID = C.CONCEPT_ID
	GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, CONCEPT_NAME,
			TARGET_CONCEPT_ID, TARGET_DOMAIN_ID, CONDITION_CONCEPT_ID
	--ORDER BY COUNT(*) DESC

	UNION ALL

	SELECT @source_short_name AS DB,
			'PROCEDURE_OCCURRENCE' AS CURRENT_LOCATION,
			SOURCE_CODE,
			SOURCE_VOCABULARY_ID,
			CONCEPT_NAME AS SOURCE_CONCEPT_NAME,
			TARGET_CONCEPT_ID AS NEW_TARGET_CONCEPT_ID,
			TARGET_DOMAIN_ID AS NEW_DOMAIN_ID,
			PROCEDURE_CONCEPT_ID AS CURRENT_CONCEPT_ID,
			COUNT(*) AS PERSON_COUNT
	FROM @cdm_database_schema.PROCEDURE_OCCURRENCE CO
	JOIN @target_database_schema.@new_maps_table NM
		ON CO.PROCEDURE_SOURCE_CONCEPT_ID = NM.SOURCE_CONCEPT_ID
	JOIN @new_vocab_schema.CONCEPT C
		ON NM.SOURCE_CONCEPT_ID = C.CONCEPT_ID
	GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, CONCEPT_NAME,
			TARGET_CONCEPT_ID, TARGET_DOMAIN_ID, PROCEDURE_CONCEPT_ID
	--ORDER BY COUNT(*) DESC

	UNION ALL

	SELECT @source_short_name AS DB,
			'DRUG_EXPOSURE' AS CURRENT_LOCATION,
			SOURCE_CODE,
			SOURCE_VOCABULARY_ID,
			CONCEPT_NAME AS SOURCE_CONCEPT_NAME,
			TARGET_CONCEPT_ID AS NEW_TARGET_CONCEPT_ID,
			TARGET_DOMAIN_ID AS NEW_DOMAIN_ID,
			DRUG_CONCEPT_ID AS CURRENT_CONCEPT_ID,
			COUNT(*) AS PERSON_COUNT
	FROM @cdm_database_schema.DRUG_EXPOSURE CO
	JOIN @target_database_schema.@new_maps_table NM
		ON CO.DRUG_SOURCE_CONCEPT_ID = NM.SOURCE_CONCEPT_ID
	JOIN @new_vocab_schema.CONCEPT C
		ON NM.SOURCE_CONCEPT_ID = C.CONCEPT_ID
	GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, CONCEPT_NAME,
			TARGET_CONCEPT_ID, TARGET_DOMAIN_ID, DRUG_CONCEPT_ID
	--ORDER BY COUNT(*) DESC

	UNION ALL

	SELECT @source_short_name AS DB,
			'OBSERVATION' AS CURRENT_LOCATION,
			SOURCE_CODE,
			SOURCE_VOCABULARY_ID,
			CONCEPT_NAME AS SOURCE_CONCEPT_NAME,
			TARGET_CONCEPT_ID AS NEW_TARGET_CONCEPT_ID,
			TARGET_DOMAIN_ID AS NEW_DOMAIN_ID,
			OBSERVATION_CONCEPT_ID AS CURRENT_CONCEPT_ID,
			COUNT(*) AS PERSON_COUNT
	FROM @cdm_database_schema.OBSERVATION CO
	JOIN @target_database_schema.@new_maps_table NM
		ON CO.OBSERVATION_SOURCE_CONCEPT_ID = NM.SOURCE_CONCEPT_ID
	JOIN @new_vocab_schema.CONCEPT C
		ON NM.SOURCE_CONCEPT_ID = C.CONCEPT_ID
	GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, CONCEPT_NAME,
			TARGET_CONCEPT_ID, TARGET_DOMAIN_ID, OBSERVATION_CONCEPT_ID
	--ORDER BY COUNT(*) DESC

	UNION ALL

	SELECT @source_short_name AS DB,
			'MEASUREMENT' AS CURRENT_LOCATION,
			SOURCE_CODE,
			SOURCE_VOCABULARY_ID,
			CONCEPT_NAME AS SOURCE_CONCEPT_NAME,
			TARGET_CONCEPT_ID AS NEW_TARGET_CONCEPT_ID,
			TARGET_DOMAIN_ID AS NEW_DOMAIN_ID,
			MEASUREMENT_CONCEPT_ID AS CURRENT_CONCEPT_ID,
			COUNT(*) AS PERSON_COUNT
	FROM @cdm_database_schema.MEASUREMENT CO
	JOIN @target_database_schema.@new_maps_table NM
		ON CO.MEASUREMENT_SOURCE_CONCEPT_ID = NM.SOURCE_CONCEPT_ID
	JOIN @new_vocab_schema.CONCEPT C
		ON NM.SOURCE_CONCEPT_ID = C.CONCEPT_ID
	GROUP BY SOURCE_CODE, SOURCE_VOCABULARY_ID, CONCEPT_NAME,
			TARGET_CONCEPT_ID, TARGET_DOMAIN_ID, MEASUREMENT_CONCEPT_ID
	--ORDER BY COUNT(*) DESC
) a
;

insert into @target_database_schema.@new_maps_cdm_table (
    db,
    current_location,
    source_code,
	source_vocabulary_id,
	source_concept_name,
	new_target_concept_id,
	new_domain_id,
	current_concept_id,
    person_count
)

SELECT *
FROM #newMaps;
