IF OBJECT_ID('tempdb..#SOURCE_TO_STANDARD_OLD') IS NOT NULL
    DROP TABLE tempdb..#SOURCE_TO_STANDARD_OLD;

SELECT *
INTO #SOURCE_TO_STANDARD_OLD
FROM (

	SELECT cast(c.concept_id as varchar)+'-'+cast(c1.concept_id as varchar) as UNIQUE_ID, c.concept_code AS SOURCE_CODE, c.concept_id AS SOURCE_CONCEPT_ID, c.concept_name AS SOURCE_CODE_DESCRIPTION,
			c.vocabulary_id AS SOURCE_VOCABULARY_ID, c.domain_id AS SOURCE_DOMAIN_ID, c.CONCEPT_CLASS_ID AS SOURCE_CONCEPT_CLASS_ID,
			c.VALID_START_DATE AS SOURCE_VALID_START_DATE, c.VALID_END_DATE AS SOURCE_VALID_END_DATE, c.INVALID_REASON AS SOURCE_INVALID_REASON,
			c1.concept_id AS TARGET_CONCEPT_ID, c1.concept_name AS TARGET_CONCEPT_NAME, c1.VOCABULARY_ID AS TARGET_VOCABUALRY_ID,
			c1.domain_id AS TARGET_DOMAIN_ID, c1.concept_class_id AS TARGET_CONCEPT_CLASS_ID,c1.INVALID_REASON AS TARGET_INVALID_REASON,
			c1.standard_concept AS TARGET_STANDARD_CONCEPT
	FROM @oldVocabSchema.CONCEPT C
		JOIN @oldVocabSchema.CONCEPT_RELATIONSHIP CR
			ON C.CONCEPT_ID = CR.CONCEPT_ID_1
			AND CR.invalid_reason IS NULL
			AND lower(cr.relationship_id) = 'maps to'
		JOIN @oldVocabSchema.CONCEPT C1
			ON CR.CONCEPT_ID_2 = C1.CONCEPT_ID
			AND C1.INVALID_REASON IS NULL
	UNION
	SELECT CAST(source_concept_id as varchar)+'-'+cast(TARGET_CONCEPT_ID as varchar) as UNIQUE_ID, source_code, SOURCE_CONCEPT_ID, SOURCE_CODE_DESCRIPTION, source_vocabulary_id, c1.domain_id AS SOURCE_DOMAIN_ID,
			c2.CONCEPT_CLASS_ID AS SOURCE_CONCEPT_CLASS_ID, c1.VALID_START_DATE AS SOURCE_VALID_START_DATE,
			c1.VALID_END_DATE AS SOURCE_VALID_END_DATE, stcm.INVALID_REASON AS SOURCE_INVALID_REASON,
			target_concept_id, c2.CONCEPT_NAME AS TARGET_CONCEPT_NAME, target_vocabulary_id, c2.domain_id AS TARGET_DOMAIN_ID,
			c2.concept_class_id AS TARGET_CONCEPT_CLASS_ID,c2.INVALID_REASON AS TARGET_INVALID_REASON,
			c2.standard_concept AS TARGET_STANDARD_CONCEPT
	FROM @oldVocabSchema.source_to_concept_map stcm
		LEFT OUTER JOIN VOCABULARY_20180609.dbo.CONCEPT c1
			ON c1.concept_id = stcm.source_concept_id
		LEFT OUTER JOIN @oldVocabSchema.CONCEPT c2
			ON c2.CONCEPT_ID = stcm.target_concept_id
	WHERE stcm.INVALID_REASON IS NULL
) STSO
;

IF OBJECT_ID('tempdb..#SOURCE_TO_STANDARD_NEW') IS NOT NULL
    DROP TABLE tempdb..#SOURCE_TO_STANDARD_NEW;

SELECT *
INTO #SOURCE_TO_STANDARD_NEW
FROM (

	SELECT cast(c.concept_id as varchar)+'-'+cast(c1.concept_id as varchar) as UNIQUE_ID, c.concept_code AS SOURCE_CODE, c.concept_id AS SOURCE_CONCEPT_ID, c.concept_name AS SOURCE_CODE_DESCRIPTION,
			c.vocabulary_id AS SOURCE_VOCABULARY_ID, c.domain_id AS SOURCE_DOMAIN_ID, c.CONCEPT_CLASS_ID AS SOURCE_CONCEPT_CLASS_ID,
			c.VALID_START_DATE AS SOURCE_VALID_START_DATE, c.VALID_END_DATE AS SOURCE_VALID_END_DATE, c.INVALID_REASON AS SOURCE_INVALID_REASON,
			c1.concept_id AS TARGET_CONCEPT_ID, c1.concept_name AS TARGET_CONCEPT_NAME, c1.VOCABULARY_ID AS TARGET_VOCABUALRY_ID,
			c1.domain_id AS TARGET_DOMAIN_ID, c1.concept_class_id AS TARGET_CONCEPT_CLASS_ID,c1.INVALID_REASON AS TARGET_INVALID_REASON,
			c1.standard_concept AS TARGET_STANDARD_CONCEPT
	FROM @newVocabSchema.CONCEPT C
		JOIN @newVocabSchema.CONCEPT_RELATIONSHIP CR
			ON C.CONCEPT_ID = CR.CONCEPT_ID_1
			AND CR.invalid_reason IS NULL
			AND lower(cr.relationship_id) = 'maps to'
		JOIN @newVocabSchema.CONCEPT C1
			ON CR.CONCEPT_ID_2 = C1.CONCEPT_ID
			AND C1.INVALID_REASON IS NULL
	UNION
	SELECT cast(SOURCE_CONCEPT_ID as varchar)+'-'+cast(TARGET_CONCEPT_ID as varchar) as UNIQUE_ID, source_code, SOURCE_CONCEPT_ID, SOURCE_CODE_DESCRIPTION, source_vocabulary_id, c1.domain_id AS SOURCE_DOMAIN_ID,
			c2.CONCEPT_CLASS_ID AS SOURCE_CONCEPT_CLASS_ID, c1.VALID_START_DATE AS SOURCE_VALID_START_DATE,
			c1.VALID_END_DATE AS SOURCE_VALID_END_DATE, stcm.INVALID_REASON AS SOURCE_INVALID_REASON,
			target_concept_id, c2.CONCEPT_NAME AS TARGET_CONCEPT_NAME, target_vocabulary_id, c2.domain_id AS TARGET_DOMAIN_ID,
			c2.concept_class_id AS TARGET_CONCEPT_CLASS_ID,c2.INVALID_REASON AS TARGET_INVALID_REASON,
			c2.standard_concept AS TARGET_STANDARD_CONCEPT
	FROM @newVocabSchema.source_to_concept_map stcm
		LEFT OUTER JOIN @newVocabSchema.CONCEPT c1
			ON c1.concept_id = stcm.source_concept_id
		LEFT OUTER JOIN @newVocabSchema.CONCEPT c2
			ON c2.CONCEPT_ID = stcm.target_concept_id
	WHERE stcm.INVALID_REASON IS NULL
) STSN
;


IF OBJECT_ID('@target_database_schema.@new_maps_table') IS NOT NULL
    DROP TABLE @target_database_schema.@new_maps_table;
SELECT *
INTO @target_database_schema.@new_maps_table
FROM (
		SELECT *
		FROM #SOURCE_TO_STANDARD_NEW
		WHERE SOURCE_CONCEPT_ID IN (

			SELECT SOURCE_CONCEPT_ID
			FROM #SOURCE_TO_STANDARD_NEW
			EXCEPT
			SELECT SOURCE_CONCEPT_ID
			FROM #SOURCE_TO_STANDARD_OLD )
		) T1
;
